# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_ip\M1_qlhsPop.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_qlhsPop(object):
    def setupUi(self, qlhsPop):
        qlhsPop.setObjectName("qlhsPop")
        qlhsPop.setWindowModality(QtCore.Qt.NonModal)
        qlhsPop.resize(300, 300)
        qlhsPop.setMaximumSize(QtCore.QSize(500, 400))
        self.verticalLayout = QtWidgets.QVBoxLayout(qlhsPop)
        self.verticalLayout.setObjectName("verticalLayout")
        self.ldd = QtWidgets.QPushButton(qlhsPop)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ldd.sizePolicy().hasHeightForWidth())
        self.ldd.setSizePolicy(sizePolicy)
        self.ldd.setMaximumSize(QtCore.QSize(500, 50))
        self.ldd.setObjectName("ldd")
        self.verticalLayout.addWidget(self.ldd)
        self.thsm = QtWidgets.QPushButton(qlhsPop)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.thsm.sizePolicy().hasHeightForWidth())
        self.thsm.setSizePolicy(sizePolicy)
        self.thsm.setMaximumSize(QtCore.QSize(500, 50))
        self.thsm.setObjectName("thsm")
        self.verticalLayout.addWidget(self.thsm)
        self.xoahs = QtWidgets.QPushButton(qlhsPop)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.xoahs.sizePolicy().hasHeightForWidth())
        self.xoahs.setSizePolicy(sizePolicy)
        self.xoahs.setMaximumSize(QtCore.QSize(500, 50))
        self.xoahs.setObjectName("xoahs")
        self.verticalLayout.addWidget(self.xoahs)
        self.bdd = QtWidgets.QPushButton(qlhsPop)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bdd.sizePolicy().hasHeightForWidth())
        self.bdd.setSizePolicy(sizePolicy)
        self.bdd.setMaximumSize(QtCore.QSize(500, 50))
        self.bdd.setObjectName("bdd")
        self.verticalLayout.addWidget(self.bdd)
        self.tbvn = QtWidgets.QPushButton(qlhsPop)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tbvn.sizePolicy().hasHeightForWidth())
        self.tbvn.setSizePolicy(sizePolicy)
        self.tbvn.setMaximumSize(QtCore.QSize(500, 50))
        self.tbvn.setObjectName("tbvn")
        self.verticalLayout.addWidget(self.tbvn)
        self.dshs = QtWidgets.QPushButton(qlhsPop)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dshs.sizePolicy().hasHeightForWidth())
        self.dshs.setSizePolicy(sizePolicy)
        self.dshs.setMaximumSize(QtCore.QSize(500, 50))
        self.dshs.setObjectName("dshs")
        self.verticalLayout.addWidget(self.dshs)
        self.quaylai = QtWidgets.QPushButton(qlhsPop)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.quaylai.sizePolicy().hasHeightForWidth())
        self.quaylai.setSizePolicy(sizePolicy)
        self.quaylai.setMaximumSize(QtCore.QSize(500, 50))
        self.quaylai.setObjectName("quaylai")
        self.verticalLayout.addWidget(self.quaylai)

        self.retranslateUi(qlhsPop)
        QtCore.QMetaObject.connectSlotsByName(qlhsPop)

    def retranslateUi(self, qlhsPop):
        _translate = QtCore.QCoreApplication.translate
        qlhsPop.setWindowTitle(_translate("qlhsPop", "Quản Lý Học Sinh"))
        self.ldd.setText(_translate("qlhsPop", "Lọc Điểm Danh"))
        self.thsm.setText(_translate("qlhsPop", "Thêm học sinh mới"))
        self.xoahs.setText(_translate("qlhsPop", "Xóa học sinh lỗi / cũ - Đổi tình trạng học"))
        self.bdd.setText(_translate("qlhsPop", "Bảng thống kê điểm danh"))
        self.tbvn.setText(_translate("qlhsPop", "Thông báo về nhà"))
        self.dshs.setText(_translate("qlhsPop", "Danh sách toàn bộ học sinh - Thay đổi tình trạng lớp"))
        self.quaylai.setText(_translate("qlhsPop", "Quay lại"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    qlhsPop = QtWidgets.QDialog()
    ui = Ui_qlhsPop()
    ui.setupUi(qlhsPop)
    qlhsPop.show()
    sys.exit(app.exec_())
