# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_ip\M22_themgv.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_themgv(object):
    def setupUi(self, themgv):
        themgv.setObjectName("themgv")
        themgv.resize(451, 422)
        self.layoutWidget = QtWidgets.QWidget(themgv)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 431, 401))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.sogvmoi = QtWidgets.QSpinBox(self.layoutWidget)
        self.sogvmoi.setMinimum(1)
        self.sogvmoi.setObjectName("sogvmoi")
        self.horizontalLayout.addWidget(self.sogvmoi)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.but_themgv = QtWidgets.QPushButton(self.layoutWidget)
        self.but_themgv.setObjectName("but_themgv")
        self.verticalLayout.addWidget(self.but_themgv)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.addgv_view = QtWidgets.QTableWidget(self.layoutWidget)
        self.addgv_view.setObjectName("addgv_view")
        self.addgv_view.setColumnCount(2)
        self.addgv_view.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.addgv_view.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.addgv_view.setHorizontalHeaderItem(1, item)
        self.verticalLayout_2.addWidget(self.addgv_view)
        self.updatedata = QtWidgets.QPushButton(self.layoutWidget)
        self.updatedata.setObjectName("updatedata")
        self.verticalLayout_2.addWidget(self.updatedata)
        self.hoantat = QtWidgets.QPushButton(self.layoutWidget)
        self.hoantat.setObjectName("hoantat")
        self.verticalLayout_2.addWidget(self.hoantat)

        self.retranslateUi(themgv)
        QtCore.QMetaObject.connectSlotsByName(themgv)

    def retranslateUi(self, themgv):
        _translate = QtCore.QCoreApplication.translate
        themgv.setWindowTitle(_translate("themgv", "Form"))
        self.label_2.setText(_translate("themgv", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; font-weight:600;\">THÊM GIÁO VIÊN MỚI</span></p></body></html>"))
        self.label.setText(_translate("themgv", "Số giáo viên mới cần thêm"))
        self.but_themgv.setText(_translate("themgv", "Tiến hành thêm giáo viên mới"))
        item = self.addgv_view.horizontalHeaderItem(0)
        item.setText(_translate("themgv", "Mã giáo viên"))
        item = self.addgv_view.horizontalHeaderItem(1)
        item.setText(_translate("themgv", "Tên giáo viên"))
        self.updatedata.setText(_translate("themgv", "Cập nhật vào cơ sở dữ liệu"))
        self.hoantat.setText(_translate("themgv", "Hoàn tất"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    themgv = QtWidgets.QWidget()
    ui = Ui_themgv()
    ui.setupUi(themgv)
    themgv.show()
    sys.exit(app.exec_())
