# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_ip\M22_themgv.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_themgv(object):
    def setupUi(self, themgv):
        themgv.setObjectName("themgv")
        themgv.resize(320, 360)
        themgv.setMinimumSize(QtCore.QSize(320, 360))
        self.gridLayout = QtWidgets.QGridLayout(themgv)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(themgv)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.sogvmoi = QtWidgets.QSpinBox(themgv)
        self.sogvmoi.setMinimum(1)
        self.sogvmoi.setObjectName("sogvmoi")
        self.gridLayout.addWidget(self.sogvmoi, 1, 1, 1, 1)
        self.but_themgv = QtWidgets.QPushButton(themgv)
        self.but_themgv.setObjectName("but_themgv")
        self.gridLayout.addWidget(self.but_themgv, 2, 0, 1, 2)
        self.addgv_view = QtWidgets.QTableWidget(themgv)
        self.addgv_view.setMinimumSize(QtCore.QSize(300, 200))
        self.addgv_view.setObjectName("addgv_view")
        self.addgv_view.setColumnCount(2)
        self.addgv_view.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.addgv_view.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.addgv_view.setHorizontalHeaderItem(1, item)
        self.gridLayout.addWidget(self.addgv_view, 3, 0, 1, 2)
        self.updatedata = QtWidgets.QPushButton(themgv)
        self.updatedata.setObjectName("updatedata")
        self.gridLayout.addWidget(self.updatedata, 4, 0, 1, 2)
        self.hoantat = QtWidgets.QPushButton(themgv)
        self.hoantat.setObjectName("hoantat")
        self.gridLayout.addWidget(self.hoantat, 5, 0, 1, 2)
        self.label_2 = QtWidgets.QLabel(themgv)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 2)

        self.retranslateUi(themgv)
        QtCore.QMetaObject.connectSlotsByName(themgv)

    def retranslateUi(self, themgv):
        _translate = QtCore.QCoreApplication.translate
        themgv.setWindowTitle(_translate("themgv", "Form"))
        self.label.setText(_translate("themgv", "Số giáo viên mới cần thêm"))
        self.but_themgv.setText(_translate("themgv", "Tiến hành thêm giáo viên mới"))
        item = self.addgv_view.horizontalHeaderItem(0)
        item.setText(_translate("themgv", "Mã giáo viên"))
        item = self.addgv_view.horizontalHeaderItem(1)
        item.setText(_translate("themgv", "Tên giáo viên"))
        self.updatedata.setText(_translate("themgv", "Cập nhật vào cơ sở dữ liệu"))
        self.hoantat.setText(_translate("themgv", "Hoàn tất"))
        self.label_2.setText(_translate("themgv", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; font-weight:600;\">THÊM GIÁO VIÊN MỚI</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    themgv = QtWidgets.QWidget()
    ui = Ui_themgv()
    ui.setupUi(themgv)
    themgv.show()
    sys.exit(app.exec_())
