# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_ip\M24_xoagv.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_formxoagv(object):
    def setupUi(self, formxoagv):
        formxoagv.setObjectName("formxoagv")
        formxoagv.resize(741, 245)
        self.layoutWidget = QtWidgets.QWidget(formxoagv)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 721, 227))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_4.addWidget(self.label_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)
        self.magv_ip = QtWidgets.QComboBox(self.layoutWidget)
        self.magv_ip.setObjectName("magv_ip")
        self.horizontalLayout.addWidget(self.magv_ip)
        self.horizontalLayout_3.addLayout(self.horizontalLayout)
        self.hotengv = QtWidgets.QLineEdit(self.layoutWidget)
        self.hotengv.setMinimumSize(QtCore.QSize(0, 22))
        self.hotengv.setMaximumSize(QtCore.QSize(16777215, 22))
        self.hotengv.setObjectName("hotengv")
        self.horizontalLayout_3.addWidget(self.hotengv)
        self.nhapdexoa = QtWidgets.QPushButton(self.layoutWidget)
        self.nhapdexoa.setObjectName("nhapdexoa")
        self.horizontalLayout_3.addWidget(self.nhapdexoa)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_4.addWidget(self.label_5)
        self.magv_out = QtWidgets.QComboBox(self.layoutWidget)
        self.magv_out.setObjectName("magv_out")
        self.horizontalLayout_4.addWidget(self.magv_out)
        self.horizontalLayout_5.addLayout(self.horizontalLayout_4)
        self.hotengvout = QtWidgets.QLineEdit(self.layoutWidget)
        self.hotengvout.setObjectName("hotengvout")
        self.horizontalLayout_5.addWidget(self.hotengvout)
        self.loaikhoids = QtWidgets.QPushButton(self.layoutWidget)
        self.loaikhoids.setObjectName("loaikhoids")
        self.horizontalLayout_5.addWidget(self.loaikhoids)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.magv_del = QtWidgets.QLineEdit(self.layoutWidget)
        self.magv_del.setObjectName("magv_del")
        self.horizontalLayout_2.addWidget(self.magv_del)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.xoagv = QtWidgets.QPushButton(self.layoutWidget)
        self.xoagv.setObjectName("xoagv")
        self.verticalLayout.addWidget(self.xoagv)
        self.hoantat = QtWidgets.QPushButton(self.layoutWidget)
        self.hoantat.setObjectName("hoantat")
        self.verticalLayout.addWidget(self.hoantat)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)

        self.retranslateUi(formxoagv)
        QtCore.QMetaObject.connectSlotsByName(formxoagv)

    def retranslateUi(self, formxoagv):
        _translate = QtCore.QCoreApplication.translate
        formxoagv.setWindowTitle(_translate("formxoagv", "Form"))
        self.label_2.setText(_translate("formxoagv", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; font-weight:600;\">XÓA GIÁO VIÊN</span></p></body></html>"))
        self.label_3.setText(_translate("formxoagv", "Lưu ý: Xóa giáo viên sẽ xóa luôn toàn bộ phân công trên bảng phân công"))
        self.label_4.setText(_translate("formxoagv", "Mã giáo viên"))
        self.nhapdexoa.setText(_translate("formxoagv", "Nhập vào danh sách xóa"))
        self.label_5.setText(_translate("formxoagv", "Mã giáo viên"))
        self.loaikhoids.setText(_translate("formxoagv", "Loại khỏi danh sách xóa"))
        self.label.setText(_translate("formxoagv", "Danh sách các mã giáo viên để xóa"))
        self.xoagv.setText(_translate("formxoagv", "Xóa giáo viên"))
        self.hoantat.setText(_translate("formxoagv", "Hoàn tất"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    formxoagv = QtWidgets.QWidget()
    ui = Ui_formxoagv()
    ui.setupUi(formxoagv)
    formxoagv.show()
    sys.exit(app.exec_())
