# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_ip\M2_qlgv.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_quanlygiaovien(object):
    def setupUi(self, quanlygiaovien):
        quanlygiaovien.setObjectName("quanlygiaovien")
        quanlygiaovien.resize(242, 192)
        self.layoutWidget = QtWidgets.QWidget(quanlygiaovien)
        self.layoutWidget.setGeometry(QtCore.QRect(11, 12, 219, 170))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.dsgv = QtWidgets.QPushButton(self.layoutWidget)
        self.dsgv.setObjectName("dsgv")
        self.verticalLayout.addWidget(self.dsgv)
        self.themgiaovien = QtWidgets.QPushButton(self.layoutWidget)
        self.themgiaovien.setObjectName("themgiaovien")
        self.verticalLayout.addWidget(self.themgiaovien)
        self.cnpcmn = QtWidgets.QPushButton(self.layoutWidget)
        self.cnpcmn.setObjectName("cnpcmn")
        self.verticalLayout.addWidget(self.cnpcmn)
        self.xoagv = QtWidgets.QPushButton(self.layoutWidget)
        self.xoagv.setObjectName("xoagv")
        self.verticalLayout.addWidget(self.xoagv)
        self.quaylai = QtWidgets.QPushButton(self.layoutWidget)
        self.quaylai.setObjectName("quaylai")
        self.verticalLayout.addWidget(self.quaylai)

        self.retranslateUi(quanlygiaovien)
        QtCore.QMetaObject.connectSlotsByName(quanlygiaovien)

    def retranslateUi(self, quanlygiaovien):
        _translate = QtCore.QCoreApplication.translate
        quanlygiaovien.setWindowTitle(_translate("quanlygiaovien", "Form"))
        self.dsgv.setText(_translate("quanlygiaovien", "Danh sách giáo viên"))
        self.themgiaovien.setText(_translate("quanlygiaovien", "Thêm giáo viên"))
        self.cnpcmn.setText(_translate("quanlygiaovien", "Cập nhật và xóa phân công môn học"))
        self.xoagv.setText(_translate("quanlygiaovien", "Xóa giáo viên"))
        self.quaylai.setText(_translate("quanlygiaovien", "Quay lại"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    quanlygiaovien = QtWidgets.QWidget()
    ui = Ui_quanlygiaovien()
    ui.setupUi(quanlygiaovien)
    quanlygiaovien.show()
    sys.exit(app.exec_())
