# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_ip\M32_themhpdinhmuc.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_themidhp(object):
    def setupUi(self, themidhp):
        themidhp.setObjectName("themidhp")
        themidhp.resize(828, 298)
        self.gridLayout = QtWidgets.QGridLayout(themidhp)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(themidhp)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.sohs = QtWidgets.QSpinBox(themidhp)
        self.sohs.setAlignment(QtCore.Qt.AlignCenter)
        self.sohs.setObjectName("sohs")
        self.gridLayout.addWidget(self.sohs, 1, 1, 1, 1)
        self.xacnhan = QtWidgets.QPushButton(themidhp)
        self.xacnhan.setObjectName("xacnhan")
        self.gridLayout.addWidget(self.xacnhan, 1, 2, 1, 1)
        self.themidhp_view = QtWidgets.QTableWidget(themidhp)
        self.themidhp_view.setMinimumSize(QtCore.QSize(810, 200))
        self.themidhp_view.setObjectName("themidhp_view")
        self.themidhp_view.setColumnCount(8)
        self.themidhp_view.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.themidhp_view.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.themidhp_view.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.themidhp_view.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.themidhp_view.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.themidhp_view.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.themidhp_view.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.themidhp_view.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.themidhp_view.setHorizontalHeaderItem(7, item)
        self.gridLayout.addWidget(self.themidhp_view, 2, 0, 1, 3)
        self.label_2 = QtWidgets.QLabel(themidhp)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 3)
        self.updatetableinfo = QtWidgets.QPushButton(themidhp)
        self.updatetableinfo.setObjectName("updatetableinfo")
        self.gridLayout.addWidget(self.updatetableinfo, 3, 0, 1, 1)
        self.updateintodb = QtWidgets.QPushButton(themidhp)
        self.updateintodb.setObjectName("updateintodb")
        self.gridLayout.addWidget(self.updateintodb, 3, 1, 1, 1)
        self.hoantat = QtWidgets.QPushButton(themidhp)
        self.hoantat.setObjectName("hoantat")
        self.gridLayout.addWidget(self.hoantat, 3, 2, 1, 1)

        self.retranslateUi(themidhp)
        QtCore.QMetaObject.connectSlotsByName(themidhp)

    def retranslateUi(self, themidhp):
        _translate = QtCore.QCoreApplication.translate
        themidhp.setWindowTitle(_translate("themidhp", "Thêm ID học phí"))
        self.label.setText(_translate("themidhp", "Số học sinh cần thêm"))
        self.xacnhan.setText(_translate("themidhp", "Xác nhận thêm ID"))
        item = self.themidhp_view.horizontalHeaderItem(0)
        item.setText(_translate("themidhp", "ID Học phí mới"))
        item = self.themidhp_view.horizontalHeaderItem(1)
        item.setText(_translate("themidhp", "Mã học sinh"))
        item = self.themidhp_view.horizontalHeaderItem(2)
        item.setText(_translate("themidhp", "Họ tên học sinh"))
        item = self.themidhp_view.horizontalHeaderItem(3)
        item.setText(_translate("themidhp", "Mã môn học"))
        item = self.themidhp_view.horizontalHeaderItem(4)
        item.setText(_translate("themidhp", "Tên môn học"))
        item = self.themidhp_view.horizontalHeaderItem(5)
        item.setText(_translate("themidhp", "Học phí"))
        item = self.themidhp_view.horizontalHeaderItem(6)
        item.setText(_translate("themidhp", "Mã giáo viên"))
        item = self.themidhp_view.horizontalHeaderItem(7)
        item.setText(_translate("themidhp", "Họ tên giáo viên"))
        self.label_2.setText(_translate("themidhp", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; font-weight:600;\">THÊM ID HỌC PHÍ MỚI</span></p></body></html>"))
        self.updatetableinfo.setText(_translate("themidhp", "Cập nhật họ tên học sinh và họ tên giáo viên và tên môn học"))
        self.updateintodb.setText(_translate("themidhp", "Cập nhật vào cơ sở dữ liệu"))
        self.hoantat.setText(_translate("themidhp", "Hoàn tất"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    themidhp = QtWidgets.QWidget()
    ui = Ui_themidhp()
    ui.setupUi(themidhp)
    themidhp.show()
    sys.exit(app.exec_())
