# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_ip\M32_themhpdinhmuc.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_themidhp(object):
    def setupUi(self, themidhp):
        themidhp.setObjectName("themidhp")
        themidhp.resize(1121, 649)
        self.layoutWidget = QtWidgets.QWidget(themidhp)
        self.layoutWidget.setGeometry(QtCore.QRect(11, 10, 1101, 631))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.sohs = QtWidgets.QSpinBox(self.layoutWidget)
        self.sohs.setObjectName("sohs")
        self.horizontalLayout.addWidget(self.sohs)
        self.xacnhan = QtWidgets.QPushButton(self.layoutWidget)
        self.xacnhan.setObjectName("xacnhan")
        self.horizontalLayout.addWidget(self.xacnhan)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.themidhp_view = QtWidgets.QTableWidget(self.layoutWidget)
        self.themidhp_view.setObjectName("themidhp_view")
        self.themidhp_view.setColumnCount(8)
        self.themidhp_view.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.themidhp_view.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.themidhp_view.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.themidhp_view.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.themidhp_view.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.themidhp_view.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.themidhp_view.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.themidhp_view.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.themidhp_view.setHorizontalHeaderItem(7, item)
        self.verticalLayout.addWidget(self.themidhp_view)
        self.updatetableinfo = QtWidgets.QPushButton(self.layoutWidget)
        self.updatetableinfo.setObjectName("updatetableinfo")
        self.verticalLayout.addWidget(self.updatetableinfo)
        self.updateintodb = QtWidgets.QPushButton(self.layoutWidget)
        self.updateintodb.setObjectName("updateintodb")
        self.verticalLayout.addWidget(self.updateintodb)
        self.hoantat = QtWidgets.QPushButton(self.layoutWidget)
        self.hoantat.setObjectName("hoantat")
        self.verticalLayout.addWidget(self.hoantat)

        self.retranslateUi(themidhp)
        QtCore.QMetaObject.connectSlotsByName(themidhp)

    def retranslateUi(self, themidhp):
        _translate = QtCore.QCoreApplication.translate
        themidhp.setWindowTitle(_translate("themidhp", "Thêm ID học phí"))
        self.label_2.setText(_translate("themidhp", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; font-weight:600;\">THÊM ID HỌC PHÍ MỚI</span></p></body></html>"))
        self.label.setText(_translate("themidhp", "Số học sinh cần thêm"))
        self.xacnhan.setText(_translate("themidhp", "Xác nhận thêm ID"))
        item = self.themidhp_view.horizontalHeaderItem(0)
        item.setText(_translate("themidhp", "ID Học phí mới"))
        item = self.themidhp_view.horizontalHeaderItem(1)
        item.setText(_translate("themidhp", "Mã học sinh"))
        item = self.themidhp_view.horizontalHeaderItem(2)
        item.setText(_translate("themidhp", "Họ tên học sinh"))
        item = self.themidhp_view.horizontalHeaderItem(3)
        item.setText(_translate("themidhp", "Mã môn học"))
        item = self.themidhp_view.horizontalHeaderItem(4)
        item.setText(_translate("themidhp", "Tên môn học"))
        item = self.themidhp_view.horizontalHeaderItem(5)
        item.setText(_translate("themidhp", "Học phí"))
        item = self.themidhp_view.horizontalHeaderItem(6)
        item.setText(_translate("themidhp", "Mã giáo viên"))
        item = self.themidhp_view.horizontalHeaderItem(7)
        item.setText(_translate("themidhp", "Họ tên giáo viên"))
        self.updatetableinfo.setText(_translate("themidhp", "Cập nhật họ tên học sinh và họ tên giáo viên và tên môn học"))
        self.updateintodb.setText(_translate("themidhp", "Cập nhật vào cơ sở dữ liệu"))
        self.hoantat.setText(_translate("themidhp", "Hoàn tất"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    themidhp = QtWidgets.QWidget()
    ui = Ui_themidhp()
    ui.setupUi(themidhp)
    themidhp.show()
    sys.exit(app.exec_())
