# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_ip\M3_quanlyhocphi.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_quanlyhocphi(object):
    def setupUi(self, quanlyhocphi):
        quanlyhocphi.setObjectName("quanlyhocphi")
        quanlyhocphi.resize(412, 155)
        self.layoutWidget = QtWidgets.QWidget(quanlyhocphi)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 399, 135))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.xhpdmc = QtWidgets.QPushButton(self.layoutWidget)
        self.xhpdmc.setObjectName("xhpdmc")
        self.verticalLayout.addWidget(self.xhpdmc)
        self.themhpdm = QtWidgets.QPushButton(self.layoutWidget)
        self.themhpdm.setObjectName("themhpdm")
        self.verticalLayout.addWidget(self.themhpdm)
        self.gndth = QtWidgets.QPushButton(self.layoutWidget)
        self.gndth.setObjectName("gndth")
        self.verticalLayout.addWidget(self.gndth)
        self.quaylai = QtWidgets.QPushButton(self.layoutWidget)
        self.quaylai.setObjectName("quaylai")
        self.verticalLayout.addWidget(self.quaylai)

        self.retranslateUi(quanlyhocphi)
        QtCore.QMetaObject.connectSlotsByName(quanlyhocphi)

    def retranslateUi(self, quanlyhocphi):
        _translate = QtCore.QCoreApplication.translate
        quanlyhocphi.setWindowTitle(_translate("quanlyhocphi", "Quản lý học phí"))
        self.xhpdmc.setText(_translate("quanlyhocphi", "Xóa / sửa học phí định mức cũ - Kiểm tra toàn bộ tình trạng học phí"))
        self.themhpdm.setText(_translate("quanlyhocphi", "Thêm học phí định mức"))
        self.gndth.setText(_translate("quanlyhocphi", "Ghi nhận đóng tiền học và Danh sách học phí đã thu"))
        self.quaylai.setText(_translate("quanlyhocphi", "Quay lại"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    quanlyhocphi = QtWidgets.QWidget()
    ui = Ui_quanlyhocphi()
    ui.setupUi(quanlyhocphi)
    quanlyhocphi.show()
    sys.exit(app.exec_())
