# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_ip\M5_phantichloinhuan.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_phantichloinhuan(object):
    def setupUi(self, phantichloinhuan):
        phantichloinhuan.setObjectName("phantichloinhuan")
        phantichloinhuan.resize(300, 300)
        phantichloinhuan.setMaximumSize(QtCore.QSize(500, 400))
        self.verticalLayout = QtWidgets.QVBoxLayout(phantichloinhuan)
        self.verticalLayout.setObjectName("verticalLayout")
        self.bclgv = QtWidgets.QPushButton(phantichloinhuan)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bclgv.sizePolicy().hasHeightForWidth())
        self.bclgv.setSizePolicy(sizePolicy)
        self.bclgv.setObjectName("bclgv")
        self.verticalLayout.addWidget(self.bclgv)
        self.capnhatthongtin = QtWidgets.QPushButton(phantichloinhuan)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.capnhatthongtin.sizePolicy().hasHeightForWidth())
        self.capnhatthongtin.setSizePolicy(sizePolicy)
        self.capnhatthongtin.setObjectName("capnhatthongtin")
        self.verticalLayout.addWidget(self.capnhatthongtin)
        self.chiluonggv = QtWidgets.QPushButton(phantichloinhuan)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chiluonggv.sizePolicy().hasHeightForWidth())
        self.chiluonggv.setSizePolicy(sizePolicy)
        self.chiluonggv.setObjectName("chiluonggv")
        self.verticalLayout.addWidget(self.chiluonggv)
        self.lr = QtWidgets.QPushButton(phantichloinhuan)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lr.sizePolicy().hasHeightForWidth())
        self.lr.setSizePolicy(sizePolicy)
        self.lr.setObjectName("lr")
        self.verticalLayout.addWidget(self.lr)
        self.bctq = QtWidgets.QPushButton(phantichloinhuan)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bctq.sizePolicy().hasHeightForWidth())
        self.bctq.setSizePolicy(sizePolicy)
        self.bctq.setObjectName("bctq")
        self.verticalLayout.addWidget(self.bctq)
        self.bccptt = QtWidgets.QPushButton(phantichloinhuan)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bccptt.sizePolicy().hasHeightForWidth())
        self.bccptt.setSizePolicy(sizePolicy)
        self.bccptt.setObjectName("bccptt")
        self.verticalLayout.addWidget(self.bccptt)
        self.quaylai = QtWidgets.QPushButton(phantichloinhuan)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.quaylai.sizePolicy().hasHeightForWidth())
        self.quaylai.setSizePolicy(sizePolicy)
        self.quaylai.setObjectName("quaylai")
        self.verticalLayout.addWidget(self.quaylai)

        self.retranslateUi(phantichloinhuan)
        QtCore.QMetaObject.connectSlotsByName(phantichloinhuan)

    def retranslateUi(self, phantichloinhuan):
        _translate = QtCore.QCoreApplication.translate
        phantichloinhuan.setWindowTitle(_translate("phantichloinhuan", "Form"))
        self.bclgv.setText(_translate("phantichloinhuan", "Bảng chi lương giáo viên"))
        self.capnhatthongtin.setText(_translate("phantichloinhuan", "Cập nhật thông tin lương giáo viên"))
        self.chiluonggv.setText(_translate("phantichloinhuan", "Chi lương giáo viên"))
        self.lr.setText(_translate("phantichloinhuan", "Lãi ròng"))
        self.bctq.setText(_translate("phantichloinhuan", "Báo cáo tổng quan"))
        self.bccptt.setText(_translate("phantichloinhuan", "Báo cáo chi phí tổng thể"))
        self.quaylai.setText(_translate("phantichloinhuan", "Quay lại"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    phantichloinhuan = QtWidgets.QWidget()
    ui = Ui_phantichloinhuan()
    ui.setupUi(phantichloinhuan)
    phantichloinhuan.show()
    sys.exit(app.exec_())
