# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_ip\M72_guitncanhan.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_guitncn(object):
    def setupUi(self, guitncn):
        guitncn.setObjectName("guitncn")
        guitncn.resize(1069, 443)
        self.widget = QtWidgets.QWidget(guitncn)
        self.widget.setGeometry(QtCore.QRect(10, 10, 1051, 421))
        self.widget.setObjectName("widget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.verticalLayout_4.addWidget(self.label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.mahschoice = QtWidgets.QComboBox(self.widget)
        self.mahschoice.setObjectName("mahschoice")
        self.horizontalLayout.addWidget(self.mahschoice)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_6 = QtWidgets.QLabel(self.widget)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_5.addWidget(self.label_6)
        self.stuname = QtWidgets.QLineEdit(self.widget)
        self.stuname.setObjectName("stuname")
        self.verticalLayout_5.addWidget(self.stuname)
        self.horizontalLayout_2.addLayout(self.verticalLayout_5)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.fbaccid = QtWidgets.QLineEdit(self.widget)
        self.fbaccid.setObjectName("fbaccid")
        self.verticalLayout.addWidget(self.fbaccid)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.fbmessid = QtWidgets.QLineEdit(self.widget)
        self.fbmessid.setObjectName("fbmessid")
        self.verticalLayout_2.addWidget(self.fbmessid)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_4.addWidget(self.label_5)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.mess = QtWidgets.QTextEdit(self.widget)
        self.mess.setObjectName("mess")
        self.verticalLayout_3.addWidget(self.mess)
        self.sendmess = QtWidgets.QPushButton(self.widget)
        self.sendmess.setObjectName("sendmess")
        self.verticalLayout_3.addWidget(self.sendmess)
        self.quaylai = QtWidgets.QPushButton(self.widget)
        self.quaylai.setObjectName("quaylai")
        self.verticalLayout_3.addWidget(self.quaylai)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)

        self.retranslateUi(guitncn)
        QtCore.QMetaObject.connectSlotsByName(guitncn)

    def retranslateUi(self, guitncn):
        _translate = QtCore.QCoreApplication.translate
        guitncn.setWindowTitle(_translate("guitncn", "Gửi tin nhắn cá nhân"))
        self.label.setText(_translate("guitncn", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; font-weight:600;\">LIÊN HỆ HỌC SINH ĐƠN LẺ</span></p></body></html>"))
        self.label_2.setText(_translate("guitncn", "Chọn mã học sinh"))
        self.label_6.setText(_translate("guitncn", "Tên học sinh"))
        self.label_3.setText(_translate("guitncn", "FB account ID"))
        self.label_4.setText(_translate("guitncn", "FB Inbox Messenger ID"))
        self.label_5.setText(_translate("guitncn", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Nội dung tin nhắn</span></p></body></html>"))
        self.sendmess.setText(_translate("guitncn", "Gửi tin nhắn"))
        self.quaylai.setText(_translate("guitncn", "Quay lại"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    guitncn = QtWidgets.QWidget()
    ui = Ui_guitncn()
    ui.setupUi(guitncn)
    guitncn.show()
    sys.exit(app.exec_())
