# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_ip\M72_guitncanhan.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_guitncn(object):
    def setupUi(self, guitncn):
        guitncn.setObjectName("guitncn")
        guitncn.resize(467, 443)
        self.gridLayout = QtWidgets.QGridLayout(guitncn)
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(guitncn)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(guitncn)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 2, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(guitncn)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(guitncn)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 3, 1, 1)
        self.stuname = QtWidgets.QLineEdit(guitncn)
        self.stuname.setObjectName("stuname")
        self.gridLayout.addWidget(self.stuname, 3, 0, 1, 2)
        self.fbaccid = QtWidgets.QLineEdit(guitncn)
        self.fbaccid.setObjectName("fbaccid")
        self.gridLayout.addWidget(self.fbaccid, 3, 2, 1, 1)
        self.fbmessid = QtWidgets.QLineEdit(guitncn)
        self.fbmessid.setObjectName("fbmessid")
        self.gridLayout.addWidget(self.fbmessid, 3, 3, 1, 1)
        self.mess = QtWidgets.QTextEdit(guitncn)
        self.mess.setObjectName("mess")
        self.gridLayout.addWidget(self.mess, 5, 0, 1, 4)
        self.sendmess = QtWidgets.QPushButton(guitncn)
        self.sendmess.setObjectName("sendmess")
        self.gridLayout.addWidget(self.sendmess, 6, 0, 1, 2)
        self.quaylai = QtWidgets.QPushButton(guitncn)
        self.quaylai.setObjectName("quaylai")
        self.gridLayout.addWidget(self.quaylai, 6, 2, 1, 2)
        self.mahschoice = QtWidgets.QComboBox(guitncn)
        self.mahschoice.setObjectName("mahschoice")
        self.gridLayout.addWidget(self.mahschoice, 1, 2, 1, 2)
        self.label = QtWidgets.QLabel(guitncn)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 4)
        self.label_5 = QtWidgets.QLabel(guitncn)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 4, 0, 1, 4)

        self.retranslateUi(guitncn)
        QtCore.QMetaObject.connectSlotsByName(guitncn)

    def retranslateUi(self, guitncn):
        _translate = QtCore.QCoreApplication.translate
        guitncn.setWindowTitle(_translate("guitncn", "Gửi tin nhắn cá nhân"))
        self.label_2.setText(_translate("guitncn", "Chọn mã học sinh"))
        self.label_6.setText(_translate("guitncn", "Tên học sinh"))
        self.label_3.setText(_translate("guitncn", "FB account ID"))
        self.label_4.setText(_translate("guitncn", "FB Inbox Messenger ID"))
        self.sendmess.setText(_translate("guitncn", "Gửi tin nhắn"))
        self.quaylai.setText(_translate("guitncn", "Quay lại"))
        self.label.setText(_translate("guitncn", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; font-weight:600;\">LIÊN HỆ HỌC SINH ĐƠN LẺ</span></p></body></html>"))
        self.label_5.setText(_translate("guitncn", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Nội dung tin nhắn</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    guitncn = QtWidgets.QWidget()
    ui = Ui_guitncn()
    ui.setupUi(guitncn)
    guitncn.show()
    sys.exit(app.exec_())
