# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_ip\M7_thongtinlienheonline.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_M7_thongtinlienhephuhuynh(object):
    def setupUi(self, M7_thongtinlienhephuhuynh):
        M7_thongtinlienhephuhuynh.setObjectName("M7_thongtinlienhephuhuynh")
        M7_thongtinlienhephuhuynh.resize(300, 300)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(M7_thongtinlienhephuhuynh.sizePolicy().hasHeightForWidth())
        M7_thongtinlienhephuhuynh.setSizePolicy(sizePolicy)
        M7_thongtinlienhephuhuynh.setMaximumSize(QtCore.QSize(500, 400))
        self.verticalLayout = QtWidgets.QVBoxLayout(M7_thongtinlienhephuhuynh)
        self.verticalLayout.setObjectName("verticalLayout")
        self.themxoacapnhat = QtWidgets.QPushButton(M7_thongtinlienhephuhuynh)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.themxoacapnhat.sizePolicy().hasHeightForWidth())
        self.themxoacapnhat.setSizePolicy(sizePolicy)
        self.themxoacapnhat.setMaximumSize(QtCore.QSize(500, 400))
        self.themxoacapnhat.setObjectName("themxoacapnhat")
        self.verticalLayout.addWidget(self.themxoacapnhat)
        self.lhhsdonle = QtWidgets.QPushButton(M7_thongtinlienhephuhuynh)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lhhsdonle.sizePolicy().hasHeightForWidth())
        self.lhhsdonle.setSizePolicy(sizePolicy)
        self.lhhsdonle.setMaximumSize(QtCore.QSize(500, 400))
        self.lhhsdonle.setObjectName("lhhsdonle")
        self.verticalLayout.addWidget(self.lhhsdonle)
        self.lhhstheonhom = QtWidgets.QPushButton(M7_thongtinlienhephuhuynh)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lhhstheonhom.sizePolicy().hasHeightForWidth())
        self.lhhstheonhom.setSizePolicy(sizePolicy)
        self.lhhstheonhom.setMaximumSize(QtCore.QSize(500, 400))
        self.lhhstheonhom.setObjectName("lhhstheonhom")
        self.verticalLayout.addWidget(self.lhhstheonhom)
        self.lhhstheogv = QtWidgets.QPushButton(M7_thongtinlienhephuhuynh)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lhhstheogv.sizePolicy().hasHeightForWidth())
        self.lhhstheogv.setSizePolicy(sizePolicy)
        self.lhhstheogv.setMaximumSize(QtCore.QSize(500, 400))
        self.lhhstheogv.setObjectName("lhhstheogv")
        self.verticalLayout.addWidget(self.lhhstheogv)
        self.quaylai = QtWidgets.QPushButton(M7_thongtinlienhephuhuynh)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.quaylai.sizePolicy().hasHeightForWidth())
        self.quaylai.setSizePolicy(sizePolicy)
        self.quaylai.setMaximumSize(QtCore.QSize(500, 400))
        self.quaylai.setObjectName("quaylai")
        self.verticalLayout.addWidget(self.quaylai)

        self.retranslateUi(M7_thongtinlienhephuhuynh)
        QtCore.QMetaObject.connectSlotsByName(M7_thongtinlienhephuhuynh)

    def retranslateUi(self, M7_thongtinlienhephuhuynh):
        _translate = QtCore.QCoreApplication.translate
        M7_thongtinlienhephuhuynh.setWindowTitle(_translate("M7_thongtinlienhephuhuynh", "Thông tin liên hệ phụ huynh trực tuyến"))
        self.themxoacapnhat.setText(_translate("M7_thongtinlienhephuhuynh", "Thêm/xóa/Cập nhật thông tin phụ huynh"))
        self.lhhsdonle.setText(_translate("M7_thongtinlienhephuhuynh", "Liên hệ học sinh đơn lẻ"))
        self.lhhstheonhom.setText(_translate("M7_thongtinlienhephuhuynh", "Liên hệ theo nhóm"))
        self.lhhstheogv.setText(_translate("M7_thongtinlienhephuhuynh", "Liên hệ học sinh theo giáo viên giảng dạy"))
        self.quaylai.setText(_translate("M7_thongtinlienhephuhuynh", "Quay lại"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    M7_thongtinlienhephuhuynh = QtWidgets.QWidget()
    ui = Ui_M7_thongtinlienhephuhuynh()
    ui.setupUi(M7_thongtinlienhephuhuynh)
    M7_thongtinlienhephuhuynh.show()
    sys.exit(app.exec_())
