# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_ip\M14_thongkediemdanh.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_tkdiemdanhhs(object):
    def setupUi(self, tkdiemdanhhs):
        tkdiemdanhhs.setObjectName("tkdiemdanhhs")
        tkdiemdanhhs.resize(1153, 491)
        self.layoutWidget = QtWidgets.QWidget(tkdiemdanhhs)
        self.layoutWidget.setGeometry(QtCore.QRect(11, 5, 1131, 481))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.datestart = QtWidgets.QDateEdit(self.layoutWidget)
        self.datestart.setDateTime(QtCore.QDateTime(QtCore.QDate(2000, 1, 1), QtCore.QTime(0, 0, 0)))
        self.datestart.setObjectName("datestart")
        self.horizontalLayout.addWidget(self.datestart)
        self.horizontalLayout_3.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.datefin = QtWidgets.QDateEdit(self.layoutWidget)
        self.datefin.setCurrentSection(QtWidgets.QDateTimeEdit.DaySection)
        self.datefin.setObjectName("datefin")
        self.horizontalLayout_2.addWidget(self.datefin)
        self.horizontalLayout_3.addLayout(self.horizontalLayout_2)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.loc = QtWidgets.QPushButton(self.layoutWidget)
        self.loc.setObjectName("loc")
        self.verticalLayout.addWidget(self.loc)
        self.tbdiemdanh_view = QtWidgets.QTableWidget(self.layoutWidget)
        self.tbdiemdanh_view.setObjectName("tbdiemdanh_view")
        self.tbdiemdanh_view.setColumnCount(6)
        self.tbdiemdanh_view.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tbdiemdanh_view.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbdiemdanh_view.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbdiemdanh_view.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbdiemdanh_view.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbdiemdanh_view.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbdiemdanh_view.setHorizontalHeaderItem(5, item)
        self.verticalLayout.addWidget(self.tbdiemdanh_view)
        self.hoantat = QtWidgets.QPushButton(self.layoutWidget)
        self.hoantat.setObjectName("hoantat")
        self.verticalLayout.addWidget(self.hoantat)

        self.retranslateUi(tkdiemdanhhs)
        QtCore.QMetaObject.connectSlotsByName(tkdiemdanhhs)

    def retranslateUi(self, tkdiemdanhhs):
        _translate = QtCore.QCoreApplication.translate
        tkdiemdanhhs.setWindowTitle(_translate("tkdiemdanhhs", "Thống kê điểm danh học sinh"))
        self.label.setText(_translate("tkdiemdanhhs", "<html><head/><body><p align=\"center\"><span style=\" font-size:9pt; font-weight:600;\">THỐNG KÊ TOÀN BỘ THÔNG TIN ĐIỂM DANH</span></p></body></html>"))
        self.label_2.setText(_translate("tkdiemdanhhs", "Ngày bắt đầu (dd/mm/yyyy)"))
        self.datestart.setDisplayFormat(_translate("tkdiemdanhhs", "d/M/yyyy"))
        self.label_3.setText(_translate("tkdiemdanhhs", "Ngày kết thúc (dd/mm/yyyy)"))
        self.datefin.setDisplayFormat(_translate("tkdiemdanhhs", "d/M/yyyy"))
        self.loc.setText(_translate("tkdiemdanhhs", "Lọc"))
        item = self.tbdiemdanh_view.horizontalHeaderItem(0)
        item.setText(_translate("tkdiemdanhhs", "ID Điểm danh"))
        item = self.tbdiemdanh_view.horizontalHeaderItem(1)
        item.setText(_translate("tkdiemdanhhs", "Mã Học sinh"))
        item = self.tbdiemdanh_view.horizontalHeaderItem(2)
        item.setText(_translate("tkdiemdanhhs", "Tên Học sinh"))
        item = self.tbdiemdanh_view.horizontalHeaderItem(3)
        item.setText(_translate("tkdiemdanhhs", "Mã Môn học"))
        item = self.tbdiemdanh_view.horizontalHeaderItem(4)
        item.setText(_translate("tkdiemdanhhs", "Mã Nhóm"))
        item = self.tbdiemdanh_view.horizontalHeaderItem(5)
        item.setText(_translate("tkdiemdanhhs", "Ngày giờ học"))
        self.hoantat.setText(_translate("tkdiemdanhhs", "Hoàn tất"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    tkdiemdanhhs = QtWidgets.QWidget()
    ui = Ui_tkdiemdanhhs()
    ui.setupUi(tkdiemdanhhs)
    tkdiemdanhhs.show()
    sys.exit(app.exec_())
