# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_ip\M1_qlhsPop.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_qlhsPop(object):
    def setupUi(self, qlhsPop):
        qlhsPop.setObjectName("qlhsPop")
        qlhsPop.setWindowModality(QtCore.Qt.NonModal)
        qlhsPop.resize(346, 265)
        self.layoutWidget = QtWidgets.QWidget(qlhsPop)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 10, 310, 242))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.ldd = QtWidgets.QPushButton(self.layoutWidget)
        self.ldd.setObjectName("ldd")
        self.verticalLayout.addWidget(self.ldd)
        self.thsm = QtWidgets.QPushButton(self.layoutWidget)
        self.thsm.setObjectName("thsm")
        self.verticalLayout.addWidget(self.thsm)
        self.xoahs = QtWidgets.QPushButton(self.layoutWidget)
        self.xoahs.setObjectName("xoahs")
        self.verticalLayout.addWidget(self.xoahs)
        self.bdd = QtWidgets.QPushButton(self.layoutWidget)
        self.bdd.setObjectName("bdd")
        self.verticalLayout.addWidget(self.bdd)
        self.tbvn = QtWidgets.QPushButton(self.layoutWidget)
        self.tbvn.setObjectName("tbvn")
        self.verticalLayout.addWidget(self.tbvn)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.dshs = QtWidgets.QPushButton(self.layoutWidget)
        self.dshs.setObjectName("dshs")
        self.verticalLayout_2.addWidget(self.dshs)
        self.quaylai = QtWidgets.QPushButton(self.layoutWidget)
        self.quaylai.setObjectName("quaylai")
        self.verticalLayout_2.addWidget(self.quaylai)

        self.retranslateUi(qlhsPop)
        QtCore.QMetaObject.connectSlotsByName(qlhsPop)

    def retranslateUi(self, qlhsPop):
        _translate = QtCore.QCoreApplication.translate
        qlhsPop.setWindowTitle(_translate("qlhsPop", "Quản Lý Học Sinh"))
        self.ldd.setText(_translate("qlhsPop", "Lọc Điểm Danh"))
        self.thsm.setText(_translate("qlhsPop", "Thêm học sinh mới"))
        self.xoahs.setText(_translate("qlhsPop", "Xóa học sinh lỗi / cũ - Đổi tình trạng học"))
        self.bdd.setText(_translate("qlhsPop", "Bảng thống kê điểm danh"))
        self.tbvn.setText(_translate("qlhsPop", "Thông báo về nhà"))
        self.dshs.setText(_translate("qlhsPop", "Danh sách toàn bộ học sinh - Thay đổi tình trạng lớp"))
        self.quaylai.setText(_translate("qlhsPop", "Quay lại"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    qlhsPop = QtWidgets.QDialog()
    ui = Ui_qlhsPop()
    ui.setupUi(qlhsPop)
    qlhsPop.show()
    sys.exit(app.exec_())
