# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_ip\M21_dsgv.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_dsgv(object):
    def setupUi(self, dsgv):
        dsgv.setObjectName("dsgv")
        dsgv.resize(320, 400)
        dsgv.setMinimumSize(QtCore.QSize(320, 400))
        self.gridLayout = QtWidgets.QGridLayout(dsgv)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(dsgv)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 3)
        self.label_2 = QtWidgets.QLabel(dsgv)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.monday = QtWidgets.QComboBox(dsgv)
        self.monday.setObjectName("monday")
        self.gridLayout.addWidget(self.monday, 1, 1, 1, 1)
        self.loc = QtWidgets.QPushButton(dsgv)
        self.loc.setObjectName("loc")
        self.gridLayout.addWidget(self.loc, 1, 2, 1, 1)
        self.gv_view = QtWidgets.QTableWidget(dsgv)
        self.gv_view.setMinimumSize(QtCore.QSize(300, 300))
        self.gv_view.setObjectName("gv_view")
        self.gv_view.setColumnCount(2)
        self.gv_view.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.gv_view.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.gv_view.setHorizontalHeaderItem(1, item)
        self.gridLayout.addWidget(self.gv_view, 2, 0, 1, 3)
        self.hoantat = QtWidgets.QPushButton(dsgv)
        self.hoantat.setObjectName("hoantat")
        self.gridLayout.addWidget(self.hoantat, 3, 0, 1, 3)

        self.retranslateUi(dsgv)
        QtCore.QMetaObject.connectSlotsByName(dsgv)

    def retranslateUi(self, dsgv):
        _translate = QtCore.QCoreApplication.translate
        dsgv.setWindowTitle(_translate("dsgv", "Số lượng giáo viên"))
        self.label.setText(_translate("dsgv", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; font-weight:600;\">DANH SÁCH GIÁO VIÊN</span></p></body></html>"))
        self.label_2.setText(_translate("dsgv", "Môn dạy"))
        self.loc.setText(_translate("dsgv", "Lọc giáo viên"))
        item = self.gv_view.horizontalHeaderItem(0)
        item.setText(_translate("dsgv", "Mã giáo viên"))
        item = self.gv_view.horizontalHeaderItem(1)
        item.setText(_translate("dsgv", "Tên giáo viên"))
        self.hoantat.setText(_translate("dsgv", "Hoàn tất"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    dsgv = QtWidgets.QDialog()
    ui = Ui_dsgv()
    ui.setupUi(dsgv)
    dsgv.show()
    sys.exit(app.exec_())
