# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_ip\M21_dsgv.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_dsgv(object):
    def setupUi(self, dsgv):
        dsgv.setObjectName("dsgv")
        dsgv.resize(523, 541)
        self.layoutWidget = QtWidgets.QWidget(dsgv)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 501, 521))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.monday = QtWidgets.QComboBox(self.layoutWidget)
        self.monday.setObjectName("monday")
        self.horizontalLayout.addWidget(self.monday)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)
        self.loc = QtWidgets.QPushButton(self.layoutWidget)
        self.loc.setObjectName("loc")
        self.horizontalLayout_2.addWidget(self.loc)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.gv_view = QtWidgets.QTableWidget(self.layoutWidget)
        self.gv_view.setObjectName("gv_view")
        self.gv_view.setColumnCount(2)
        self.gv_view.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.gv_view.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.gv_view.setHorizontalHeaderItem(1, item)
        self.verticalLayout.addWidget(self.gv_view)
        self.hoantat = QtWidgets.QPushButton(self.layoutWidget)
        self.hoantat.setObjectName("hoantat")
        self.verticalLayout.addWidget(self.hoantat)

        self.retranslateUi(dsgv)
        QtCore.QMetaObject.connectSlotsByName(dsgv)

    def retranslateUi(self, dsgv):
        _translate = QtCore.QCoreApplication.translate
        dsgv.setWindowTitle(_translate("dsgv", "Số lượng giáo viên"))
        self.label.setText(_translate("dsgv", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; font-weight:600;\">DANH SÁCH GIÁO VIÊN</span></p></body></html>"))
        self.label_2.setText(_translate("dsgv", "Môn dạy"))
        self.loc.setText(_translate("dsgv", "Lọc giáo viên"))
        item = self.gv_view.horizontalHeaderItem(0)
        item.setText(_translate("dsgv", "Mã giáo viên"))
        item = self.gv_view.horizontalHeaderItem(1)
        item.setText(_translate("dsgv", "Tên giáo viên"))
        self.hoantat.setText(_translate("dsgv", "Hoàn tất"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    dsgv = QtWidgets.QDialog()
    ui = Ui_dsgv()
    ui.setupUi(dsgv)
    dsgv.show()
    sys.exit(app.exec_())
