# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_ip\M24_xoagv.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_formxoagv(object):
    def setupUi(self, formxoagv):
        formxoagv.setObjectName("formxoagv")
        formxoagv.resize(560, 195)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(195)
        sizePolicy.setHeightForWidth(formxoagv.sizePolicy().hasHeightForWidth())
        formxoagv.setSizePolicy(sizePolicy)
        formxoagv.setMinimumSize(QtCore.QSize(560, 195))
        formxoagv.setMaximumSize(QtCore.QSize(16777215, 195))
        self.gridLayout = QtWidgets.QGridLayout(formxoagv)
        self.gridLayout.setObjectName("gridLayout")
        self.label_3 = QtWidgets.QLabel(formxoagv)
        self.label_3.setMaximumSize(QtCore.QSize(300, 20))
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 5)
        self.label_4 = QtWidgets.QLabel(formxoagv)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 0, 1, 1)
        self.magv_ip = QtWidgets.QComboBox(formxoagv)
        self.magv_ip.setObjectName("magv_ip")
        self.gridLayout.addWidget(self.magv_ip, 2, 1, 1, 1)
        self.hotengv = QtWidgets.QLineEdit(formxoagv)
        self.hotengv.setMinimumSize(QtCore.QSize(0, 22))
        self.hotengv.setMaximumSize(QtCore.QSize(16777215, 22))
        self.hotengv.setObjectName("hotengv")
        self.gridLayout.addWidget(self.hotengv, 2, 2, 1, 2)
        self.nhapdexoa = QtWidgets.QPushButton(formxoagv)
        self.nhapdexoa.setObjectName("nhapdexoa")
        self.gridLayout.addWidget(self.nhapdexoa, 2, 4, 1, 1)
        self.label_5 = QtWidgets.QLabel(formxoagv)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 3, 0, 1, 1)
        self.magv_out = QtWidgets.QComboBox(formxoagv)
        self.magv_out.setObjectName("magv_out")
        self.gridLayout.addWidget(self.magv_out, 3, 1, 1, 1)
        self.hotengvout = QtWidgets.QLineEdit(formxoagv)
        self.hotengvout.setObjectName("hotengvout")
        self.gridLayout.addWidget(self.hotengvout, 3, 2, 1, 2)
        self.loaikhoids = QtWidgets.QPushButton(formxoagv)
        self.loaikhoids.setObjectName("loaikhoids")
        self.gridLayout.addWidget(self.loaikhoids, 3, 4, 1, 1)
        self.xoagv = QtWidgets.QPushButton(formxoagv)
        self.xoagv.setObjectName("xoagv")
        self.gridLayout.addWidget(self.xoagv, 5, 0, 1, 5)
        self.hoantat = QtWidgets.QPushButton(formxoagv)
        self.hoantat.setObjectName("hoantat")
        self.gridLayout.addWidget(self.hoantat, 6, 0, 1, 5)
        self.label = QtWidgets.QLabel(formxoagv)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 4, 0, 1, 1)
        self.magv_del = QtWidgets.QLineEdit(formxoagv)
        self.magv_del.setObjectName("magv_del")
        self.gridLayout.addWidget(self.magv_del, 4, 1, 1, 4)
        self.label_2 = QtWidgets.QLabel(formxoagv)
        self.label_2.setMaximumSize(QtCore.QSize(510, 20))
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 1, 1, 3)

        self.retranslateUi(formxoagv)
        QtCore.QMetaObject.connectSlotsByName(formxoagv)

    def retranslateUi(self, formxoagv):
        _translate = QtCore.QCoreApplication.translate
        formxoagv.setWindowTitle(_translate("formxoagv", "Form"))
        self.label_3.setText(_translate("formxoagv", "Lưu ý: Xóa giáo viên sẽ xóa luôn toàn bộ phân công trên bảng phân công"))
        self.label_4.setText(_translate("formxoagv", "Mã giáo viên"))
        self.nhapdexoa.setText(_translate("formxoagv", "Nhập vào danh sách xóa"))
        self.label_5.setText(_translate("formxoagv", "Mã giáo viên"))
        self.loaikhoids.setText(_translate("formxoagv", "Loại khỏi danh sách xóa"))
        self.xoagv.setText(_translate("formxoagv", "Xóa giáo viên"))
        self.hoantat.setText(_translate("formxoagv", "Hoàn tất"))
        self.label.setText(_translate("formxoagv", "Danh sách các mã giáo viên để xóa"))
        self.label_2.setText(_translate("formxoagv", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; font-weight:600;\">XÓA GIÁO VIÊN</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    formxoagv = QtWidgets.QWidget()
    ui = Ui_formxoagv()
    ui.setupUi(formxoagv)
    formxoagv.show()
    sys.exit(app.exec_())
