# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_ip\M2_qlgv.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_quanlygiaovien(object):
    def setupUi(self, quanlygiaovien):
        quanlygiaovien.setObjectName("quanlygiaovien")
        quanlygiaovien.resize(300, 300)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(quanlygiaovien.sizePolicy().hasHeightForWidth())
        quanlygiaovien.setSizePolicy(sizePolicy)
        quanlygiaovien.setMaximumSize(QtCore.QSize(500, 400))
        self.verticalLayout = QtWidgets.QVBoxLayout(quanlygiaovien)
        self.verticalLayout.setObjectName("verticalLayout")
        self.dsgv = QtWidgets.QPushButton(quanlygiaovien)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dsgv.sizePolicy().hasHeightForWidth())
        self.dsgv.setSizePolicy(sizePolicy)
        self.dsgv.setObjectName("dsgv")
        self.verticalLayout.addWidget(self.dsgv)
        self.themgiaovien = QtWidgets.QPushButton(quanlygiaovien)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.themgiaovien.sizePolicy().hasHeightForWidth())
        self.themgiaovien.setSizePolicy(sizePolicy)
        self.themgiaovien.setObjectName("themgiaovien")
        self.verticalLayout.addWidget(self.themgiaovien)
        self.cnpcmn = QtWidgets.QPushButton(quanlygiaovien)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cnpcmn.sizePolicy().hasHeightForWidth())
        self.cnpcmn.setSizePolicy(sizePolicy)
        self.cnpcmn.setObjectName("cnpcmn")
        self.verticalLayout.addWidget(self.cnpcmn)
        self.xoagv = QtWidgets.QPushButton(quanlygiaovien)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.xoagv.sizePolicy().hasHeightForWidth())
        self.xoagv.setSizePolicy(sizePolicy)
        self.xoagv.setObjectName("xoagv")
        self.verticalLayout.addWidget(self.xoagv)
        self.quaylai = QtWidgets.QPushButton(quanlygiaovien)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.quaylai.sizePolicy().hasHeightForWidth())
        self.quaylai.setSizePolicy(sizePolicy)
        self.quaylai.setObjectName("quaylai")
        self.verticalLayout.addWidget(self.quaylai)

        self.retranslateUi(quanlygiaovien)
        QtCore.QMetaObject.connectSlotsByName(quanlygiaovien)

    def retranslateUi(self, quanlygiaovien):
        _translate = QtCore.QCoreApplication.translate
        quanlygiaovien.setWindowTitle(_translate("quanlygiaovien", "Form"))
        self.dsgv.setText(_translate("quanlygiaovien", "Danh sách giáo viên"))
        self.themgiaovien.setText(_translate("quanlygiaovien", "Thêm giáo viên"))
        self.cnpcmn.setText(_translate("quanlygiaovien", "Cập nhật và xóa phân công môn học"))
        self.xoagv.setText(_translate("quanlygiaovien", "Xóa giáo viên"))
        self.quaylai.setText(_translate("quanlygiaovien", "Quay lại"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    quanlygiaovien = QtWidgets.QWidget()
    ui = Ui_quanlygiaovien()
    ui.setupUi(quanlygiaovien)
    quanlygiaovien.show()
    sys.exit(app.exec_())
