# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_ip\M3_quanlyhocphi.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_quanlyhocphi(object):
    def setupUi(self, quanlyhocphi):
        quanlyhocphi.setObjectName("quanlyhocphi")
        quanlyhocphi.resize(345, 200)
        quanlyhocphi.setMaximumSize(QtCore.QSize(500, 400))
        self.verticalLayout = QtWidgets.QVBoxLayout(quanlyhocphi)
        self.verticalLayout.setObjectName("verticalLayout")
        self.xhpdmc = QtWidgets.QPushButton(quanlyhocphi)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.xhpdmc.sizePolicy().hasHeightForWidth())
        self.xhpdmc.setSizePolicy(sizePolicy)
        self.xhpdmc.setObjectName("xhpdmc")
        self.verticalLayout.addWidget(self.xhpdmc)
        self.themhpdm = QtWidgets.QPushButton(quanlyhocphi)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.themhpdm.sizePolicy().hasHeightForWidth())
        self.themhpdm.setSizePolicy(sizePolicy)
        self.themhpdm.setObjectName("themhpdm")
        self.verticalLayout.addWidget(self.themhpdm)
        self.gndth = QtWidgets.QPushButton(quanlyhocphi)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gndth.sizePolicy().hasHeightForWidth())
        self.gndth.setSizePolicy(sizePolicy)
        self.gndth.setObjectName("gndth")
        self.verticalLayout.addWidget(self.gndth)
        self.quaylai = QtWidgets.QPushButton(quanlyhocphi)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.quaylai.sizePolicy().hasHeightForWidth())
        self.quaylai.setSizePolicy(sizePolicy)
        self.quaylai.setObjectName("quaylai")
        self.verticalLayout.addWidget(self.quaylai)

        self.retranslateUi(quanlyhocphi)
        QtCore.QMetaObject.connectSlotsByName(quanlyhocphi)

    def retranslateUi(self, quanlyhocphi):
        _translate = QtCore.QCoreApplication.translate
        quanlyhocphi.setWindowTitle(_translate("quanlyhocphi", "Quản lý học phí"))
        self.xhpdmc.setText(_translate("quanlyhocphi", "Xóa / sửa học phí định mức cũ - Kiểm tra toàn bộ tình trạng học phí"))
        self.themhpdm.setText(_translate("quanlyhocphi", "Thêm học phí định mức"))
        self.gndth.setText(_translate("quanlyhocphi", "Ghi nhận đóng tiền học và Danh sách học phí đã thu"))
        self.quaylai.setText(_translate("quanlyhocphi", "Quay lại"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    quanlyhocphi = QtWidgets.QWidget()
    ui = Ui_quanlyhocphi()
    ui.setupUi(quanlyhocphi)
    quanlyhocphi.show()
    sys.exit(app.exec_())
