# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_ip\M4_phanmonnhomtkb.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_phanmonnhomtkb(object):
    def setupUi(self, phanmonnhomtkb):
        phanmonnhomtkb.setObjectName("phanmonnhomtkb")
        phanmonnhomtkb.resize(206, 186)
        self.layoutWidget = QtWidgets.QWidget(phanmonnhomtkb)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 188, 170))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(1, 1, 1, 1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lkthemxoanhom = QtWidgets.QPushButton(self.layoutWidget)
        self.lkthemxoanhom.setObjectName("lkthemxoanhom")
        self.verticalLayout.addWidget(self.lkthemxoanhom)
        self.cnhstn = QtWidgets.QPushButton(self.layoutWidget)
        self.cnhstn.setObjectName("cnhstn")
        self.verticalLayout.addWidget(self.cnhstn)
        self.dtkbn = QtWidgets.QPushButton(self.layoutWidget)
        self.dtkbn.setObjectName("dtkbn")
        self.verticalLayout.addWidget(self.dtkbn)
        self.quaylai = QtWidgets.QPushButton(self.layoutWidget)
        self.quaylai.setObjectName("quaylai")
        self.verticalLayout.addWidget(self.quaylai)

        self.retranslateUi(phanmonnhomtkb)
        QtCore.QMetaObject.connectSlotsByName(phanmonnhomtkb)

    def retranslateUi(self, phanmonnhomtkb):
        _translate = QtCore.QCoreApplication.translate
        phanmonnhomtkb.setWindowTitle(_translate("phanmonnhomtkb", "Form"))
        self.lkthemxoanhom.setText(_translate("phanmonnhomtkb", "Liệt kê/Thêm/Xóa nhóm"))
        self.cnhstn.setText(_translate("phanmonnhomtkb", "Cập nhật học sinh trong nhóm"))
        self.dtkbn.setText(_translate("phanmonnhomtkb", "Thêm/Đổi thời khóa biểu nhóm"))
        self.quaylai.setText(_translate("phanmonnhomtkb", "Quay lại"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    phanmonnhomtkb = QtWidgets.QWidget()
    ui = Ui_phanmonnhomtkb()
    ui.setupUi(phanmonnhomtkb)
    phanmonnhomtkb.show()
    sys.exit(app.exec_())
