# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_ip\M6_quanlybaihocgiohoc.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_quanlybaihocgiohoc(object):
    def setupUi(self, quanlybaihocgiohoc):
        quanlybaihocgiohoc.setObjectName("quanlybaihocgiohoc")
        quanlybaihocgiohoc.resize(300, 200)
        quanlybaihocgiohoc.setMaximumSize(QtCore.QSize(500, 400))
        self.verticalLayout = QtWidgets.QVBoxLayout(quanlybaihocgiohoc)
        self.verticalLayout.setObjectName("verticalLayout")
        self.cnttcn = QtWidgets.QPushButton(quanlybaihocgiohoc)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cnttcn.sizePolicy().hasHeightForWidth())
        self.cnttcn.setSizePolicy(sizePolicy)
        self.cnttcn.setObjectName("cnttcn")
        self.verticalLayout.addWidget(self.cnttcn)
        self.cnttn = QtWidgets.QPushButton(quanlybaihocgiohoc)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cnttn.sizePolicy().hasHeightForWidth())
        self.cnttn.setSizePolicy(sizePolicy)
        self.cnttn.setObjectName("cnttn")
        self.verticalLayout.addWidget(self.cnttn)
        self.utthvnchs = QtWidgets.QPushButton(quanlybaihocgiohoc)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.utthvnchs.sizePolicy().hasHeightForWidth())
        self.utthvnchs.setSizePolicy(sizePolicy)
        self.utthvnchs.setObjectName("utthvnchs")
        self.verticalLayout.addWidget(self.utthvnchs)
        self.quaylai = QtWidgets.QPushButton(quanlybaihocgiohoc)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.quaylai.sizePolicy().hasHeightForWidth())
        self.quaylai.setSizePolicy(sizePolicy)
        self.quaylai.setObjectName("quaylai")
        self.verticalLayout.addWidget(self.quaylai)

        self.retranslateUi(quanlybaihocgiohoc)
        QtCore.QMetaObject.connectSlotsByName(quanlybaihocgiohoc)

    def retranslateUi(self, quanlybaihocgiohoc):
        _translate = QtCore.QCoreApplication.translate
        quanlybaihocgiohoc.setWindowTitle(_translate("quanlybaihocgiohoc", "Form"))
        self.cnttcn.setText(_translate("quanlybaihocgiohoc", "Cập nhật tiến trình cá nhân"))
        self.cnttn.setText(_translate("quanlybaihocgiohoc", "Cập nhật tiến trình nhóm"))
        self.utthvnchs.setText(_translate("quanlybaihocgiohoc", "Update tình trạng học và nghỉ của học sinh"))
        self.quaylai.setText(_translate("quanlybaihocgiohoc", "Quay lại"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    quanlybaihocgiohoc = QtWidgets.QWidget()
    ui = Ui_quanlybaihocgiohoc()
    ui.setupUi(quanlybaihocgiohoc)
    quanlybaihocgiohoc.show()
    sys.exit(app.exec_())
