# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_ip\MainWin.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(569, 441)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(140, 90, 291, 251))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.qlhs = QtWidgets.QPushButton(self.layoutWidget)
        self.qlhs.setMinimumSize(QtCore.QSize(111, 28))
        self.qlhs.setObjectName("qlhs")
        self.verticalLayout.addWidget(self.qlhs)
        self.qlgv = QtWidgets.QPushButton(self.layoutWidget)
        self.qlgv.setMinimumSize(QtCore.QSize(93, 28))
        self.qlgv.setObjectName("qlgv")
        self.verticalLayout.addWidget(self.qlgv)
        self.qlhp = QtWidgets.QPushButton(self.layoutWidget)
        self.qlhp.setMinimumSize(QtCore.QSize(93, 28))
        self.qlhp.setObjectName("qlhp")
        self.verticalLayout.addWidget(self.qlhp)
        self.pmvn = QtWidgets.QPushButton(self.layoutWidget)
        self.pmvn.setMinimumSize(QtCore.QSize(93, 28))
        self.pmvn.setObjectName("pmvn")
        self.verticalLayout.addWidget(self.pmvn)
        self.qlbhgh = QtWidgets.QPushButton(self.layoutWidget)
        self.qlbhgh.setObjectName("qlbhgh")
        self.verticalLayout.addWidget(self.qlbhgh)
        self.ptln = QtWidgets.QPushButton(self.layoutWidget)
        self.ptln.setMinimumSize(QtCore.QSize(93, 28))
        self.ptln.setObjectName("ptln")
        self.verticalLayout.addWidget(self.ptln)
        self.stuconnect = QtWidgets.QPushButton(self.layoutWidget)
        self.stuconnect.setObjectName("stuconnect")
        self.verticalLayout.addWidget(self.stuconnect)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.qlhs.setText(_translate("MainWindow", "Quản Lý Học Sinh"))
        self.qlgv.setText(_translate("MainWindow", "Quản Lý Giáo Viên"))
        self.qlhp.setText(_translate("MainWindow", "Quản Lý Học Phí"))
        self.pmvn.setText(_translate("MainWindow", "Phân môn, nhóm và thời khóa biểu nhóm"))
        self.qlbhgh.setText(_translate("MainWindow", "Quản lý bài học cá nhân và nhóm"))
        self.ptln.setText(_translate("MainWindow", "Phân tích lợi nhuận"))
        self.stuconnect.setText(_translate("MainWindow", "Thông tin liên hệ phụ huynh trực tuyến"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
